language: ruby
rvm:
- 2.2.0
- 2.1.5
- 2.0.0
- 1.9.3
- jruby-1.7.9
- jruby-head
script: LD_LIBRARY_PATH=lib bundle exec rake travis
notifications:
  email: false
matrix:
  allow_failures:
  - rvm: jruby-head
